name: Build .deb on push

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Build Debian package
        uses: jtdor/build-deb-action@v1
        with:
          buildpackage-opts: -b -us -uc

      - name: Upload Debian artifacts
        uses: actions/upload-artifact@v7
        with:
          name: debian-package
          path: debian/artifacts/
